server:
  port: 9098
spring:
  redis:
    host: 192.168.50.13
    port: 6379
    # password:
    database: 6
    lettuce:
      pool:
        max-active: 10
        max-idle: 5
        min-idle: 1
        max-wait: 5000ms
  application:
    name: RedisStreamDemo
mail:
  sender:
    retry:
      times: 15
      duration: 5000 # ms
